
[COMMON]
DEBUG : True
# units seconds
RESPONSE_LATENCY : 60

[DEVICE]
DRIVER_NAME: Alex Courouble
DRIVER_ID: AC007
VEHICLE_MODEL: BMW
VEHICLE_ID: BMW1234

# Pre-recorded device data
DEVICE_DATA_FILENAME: data/car_data.csv

# SENSORS
SENSORS: 
  - OBD
  - GPS
OBD_METRICS: 
  - SPEED
  - RPM
  - FUEL_LEVEL
  - ABSOLUTE_LOAD
  - ENGINE_LOAD
  - RELATIVE_THROTTLE_POS
  - THROTTLE_POS_B

GPS_METRICS: ...

DISTANCE_UNITS_LABEL: miles
GPS_SERIAL: /dev/ttyUSB0
DEFAULT_GPS: 37.7992520359445,-122.41955459117891

LIVE: True

[EDGE]
# how frequency we read from the obd sensors
SAMPLING_FREQUENCY: 0.1  
# our processing window
HISTORY: 10
MAX_READINGS: 180000 

EVENTS_FILENAME: data/events.csv
EVENTS_FILENAME_BACKUP: data/events.csv.bak

DISTANCE_TRAVELED_FILENAME: data/distance_traveled.txt
DISTANCE_TRAVELED_FILENAME_BACKUP: data/distance_traveled.txt.bak

# Stream events to Cloud Endpoints
STREAM_TO_CLOUD: False
# Record sensor data to file or other persistent store
RECORD: True

#in seconds to contact the server
# 5 minutes -- or is this too long?

REPORT_RETRY_SEC: 300
# 2 seconds
SAVE_INTERVAL_LOCAL: 2

# Applications that are enabled
INSURANCE_ENABLED: True
MY_DRIVING_ENABLED: False
SMART_CITY_ENABLED: False

[INSURANCE]
##TODO -- move to https
ENDPOINT : 0.0.0.0
PORT : 2000
VERSION : NULL
PROTOCOL : http

[SMART_CITY]
ENDPOINT : 0.0.0.0
PORT: 2001
VERSION : NULL
PROTOCOL : http

[MY_DRIVING]
ENDPOINT : 0.0.0.0
PORT : 2002
VERSION: NULL
PROTOCOL : http

